services:
  roproxy-lite:
    build: .
    container_name: roproxy-lite
    environment:
      PORT: "8080"
      TIMEOUT: "5"
      RETRIES: "5"
      # KEY: "your_secret_key"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
