services:
  roproxy-lite:
    build: .
    container_name: roproxy-lite
    environment:
      PORT: "8080"
      TIMEOUT: "5"
      RETRIES: "5"
      # KEY: "your_secret_key"
    restart: unless-stopped
